// Fixed PDF generation utility for ENVOCAP reports

export const downloadSamplePDF = () => {
  const reportId = `ENV-${Date.now()}`;
  const currentDate = new Date().toLocaleDateString();

  // Create a simple but valid PDF structure
  const pdfContent = `%PDF-1.4
1 0 obj
<<
/Type /Catalog
/Pages 2 0 R
>>
endobj

2 0 obj
<<
/Type /Pages
/Kids [3 0 R]
/Count 1
>>
endobj

3 0 obj
<<
/Type /Page
/Parent 2 0 R
/MediaBox [0 0 612 792]
/Contents 4 0 R
/Resources <<
/Font <<
/F1 5 0 R
/F2 6 0 R
>>
>>
>>
endobj

4 0 obj
<<
/Length 1800
>>
stream
BT
/F2 20 Tf
50 750 Td
(ENVOCAP ESG SUSTAINABILITY REPORT 2024) Tj
0 -25 Td
/F1 14 Tf
(Corporate Sustainability Reporting Directive \\(CSRD\\) Compliant) Tj

0 -35 Td
/F2 16 Tf
(GREEN SOLUTIONS LTD) Tj
0 -20 Td
/F1 11 Tf
(Manufacturing Sector \\(NACE C25\\) | Report ID: ${reportId}) Tj
0 -12 Td
(Reporting Period: FY 2024 | Generated: ${currentDate}) Tj
0 -12 Td
(Prepared by: ENVOCAP AI Platform) Tj

0 -30 Td
/F2 14 Tf
(EXECUTIVE SUMMARY) Tj
0 -18 Td
/F1 10 Tf
(This CSRD-compliant report presents Green Solutions Ltd's ESG) Tj
0 -10 Td
(performance for FY 2024. Key achievements: 12% carbon reduction,) Tj
0 -10 Td
(94% CSRD compliance, demonstrating European Green Deal commitment.) Tj

0 -25 Td
/F2 12 Tf
(KEY PERFORMANCE INDICATORS) Tj
0 -15 Td
/F1 9 Tf
(Carbon Footprint \\(Scope 1+2\\): 24.8 tCO2 \\(↓12%\\)) Tj
0 -10 Td
(Energy Consumption: 156.2 MWh \\(↑3%\\)) Tj
0 -10 Td
(Renewable Energy: 65% \\(↑15%\\) | Water: 2,340L \\(↓8%\\)) Tj
0 -10 Td
(Waste: 1.2t \\(↓18%\\) | Recycling: 85% \\(↑5%\\)) Tj
0 -10 Td
(Employee Satisfaction: 4.2/5 | Gender Diversity: 40%) Tj
0 -10 Td
(Safety: 0 incidents \\(180 days\\) | CSRD Score: 94%) Tj

0 -25 Td
/F2 12 Tf
(CARBON EMISSIONS BREAKDOWN) Tj
0 -15 Td
/F1 9 Tf
(Scope 1 \\(Direct\\): 8.2 tCO2 - Gas: 4.3, Vehicles: 3.9) Tj
0 -10 Td
(Scope 2 \\(Indirect\\): 16.6 tCO2 - Grid: 11.2, Offset: -5.4) Tj
0 -10 Td
(Scope 3 \\(Value Chain\\): 12.4 tCO2) Tj

0 -25 Td
/F2 12 Tf
(CSRD ENVIRONMENTAL DISCLOSURES) Tj
0 -15 Td
/F1 9 Tf
(E1-1: Climate Transition Plan - Net-zero by 2050 \\(COMPLIANT\\)) Tj
0 -10 Td
(E1-6: GHG Emissions - Scope 1-3 disclosed \\(COMPLIANT\\)) Tj
0 -10 Td
(E2-E5: Pollution, Water, Biodiversity, Circular \\(COVERED\\)) Tj

0 -25 Td
/F2 12 Tf
(DATA SOURCES & VERIFICATION) Tj
0 -15 Td
/F1 8 Tf
(Energy Bills: Green Energy Solutions \\(2.4MB, OCR: 98.7%\\)) Tj
0 -9 Td
(Fleet Data: Q4 Fuel Receipts \\(156 transactions, GPS verified\\)) Tj
0 -9 Td
(Suppliers: 23 partners \\(89% response, ISO 14001 verified\\)) Tj
0 -9 Td
(Waste: Camera scan + certificates \\(AI: 96.4% accuracy\\)) Tj
0 -9 Td
(Renewables: Vattenfall wind farm certificates \\(EU Registry\\)) Tj

0 -20 Td
/F2 10 Tf
(VERIFICATION SUMMARY) Tj
0 -12 Td
/F1 8 Tf
(Documents: 127 | Verification: 100% | Quality Score: 94%) Tj
0 -9 Td
(Third-party: Ernst & Young | Standards: DEFRA 2024, EPA, IPCC) Tj
0 -9 Td
(Audit Trail: Complete with timestamps and source validation) Tj

0 -20 Td
/F2 10 Tf
(STRATEGIC RECOMMENDATIONS) Tj
0 -12 Td
/F1 8 Tf
(Immediate: LED lighting \\(8% energy↓\\), waste segregation \\(90%\\)) Tj
0 -9 Td
(2025: 75% renewable energy, ISO 50001 certification) Tj
0 -9 Td
(2030: 50% emission reduction, 100% renewable, circular economy) Tj

0 -25 Td
/F1 7 Tf
(Generated by ENVOCAP Platform | This sample demonstrates comprehensive) Tj
0 -8 Td
(ESG reporting capabilities. For full functionality, upgrade to Pro.) Tj
0 -8 Td
(© 2024 ENVOCAP Platform. All rights reserved. | envocap.com) Tj
0 -8 Td
(Compliant with EU Regulation 2023/2772 - CSRD) Tj
ET
endstream
endobj

5 0 obj
<<
/Type /Font
/Subtype /Type1
/BaseFont /Helvetica
>>
endobj

6 0 obj
<<
/Type /Font
/Subtype /Type1
/BaseFont /Helvetica-Bold
>>
endobj

xref
0 7
0000000000 65535 f
0000000009 00000 n
0000000058 00000 n
0000000115 00000 n
0000000268 00000 n
0000002120 00000 n
0000002190 00000 n
trailer
<<
/Size 7
/Root 1 0 R
>>
startxref
2265
%%EOF`;

  // Replace template variables with actual values
  const finalPdfContent = pdfContent
    .replace('${reportId}', reportId)
    .replace('${currentDate}', currentDate);

  const blob = new Blob([finalPdfContent], { type: 'application/pdf' });
  const url = URL.createObjectURL(blob);

  const link = document.createElement('a');
  link.href = url;
  link.download = 'ENVOCAP_ESG_Report_2024.pdf';
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);

  // Clean up the URL object
  URL.revokeObjectURL(url);
};

// Generate other report formats
export const generateSamplePDF = () => {
  return downloadSamplePDF();
};

export const downloadDemoReport = () => {
  return downloadSamplePDF();
};

// Generate styled HTML report that matches website design
export const generateStyledHTMLReport = () => {
  const reportId = `ENV-${Date.now()}`;
  const currentDate = new Date().toLocaleDateString();

  return `
<!DOCTYPE html>
<html>
<head>
    <title>ENVOCAP ESG Report 2024</title>
    <meta charset="UTF-8">
    <style>
        @import url('https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700;800;900&display=swap');

        * { margin: 0; padding: 0; box-sizing: border-box; }

        body {
            font-family: 'Inter', -apple-system, BlinkMacSystemFont, sans-serif;
            line-height: 1.6;
            color: #1f2937;
            background: linear-gradient(135deg, #f0fdf4 0%, #ffffff 50%, rgba(5, 150, 105, 0.05) 100%);
            min-height: 100vh;
        }

        .container {
            max-width: 1200px;
            margin: 0 auto;
            background: white;
            box-shadow: 0 25px 50px -12px rgba(0, 0, 0, 0.25);
        }

        /* Header with ENVOCAP Branding */
        .header {
            background: white;
            color: white;
            padding: 3rem;
            position: relative;
            overflow: hidden;
        }

        .header::before {
            content: '';
            position: absolute;
            top: -50px;
            left: -50px;
            width: 160px;
            height: 160px;
            background: rgba(255,255,255,0.05);
            border-radius: 50%;
        }

        .logo-section {
            display: flex;
            align-items: center;
            margin-bottom: 2rem;
            position: relative;
            z-index: 10;
        }

        .logo {
            height: 1.25rem;
            margin-right: 0.75rem;
        }

        .main-title {
            font-size: clamp(2rem, 5vw, 4rem);
            font-weight: 900;
            margin-bottom: 1rem;
            line-height: 1.1;
            color: #000000;
        }

        .subtitle {
            font-size: clamp(1rem, 2vw, 1.5rem);
            font-weight: 600;
            color: #959595;
            margin-bottom: 2rem;
        }

        .compliance-badges {
            display: flex;
            flex-wrap: wrap;
            gap: 1rem;
            margin-top: 2rem;
        }

        .badge {
            background: white;
            padding: 0.5rem 1rem;
            border-radius: 1.5rem;
            font-size: 0.75rem;
            font-weight: 700;
            border: 1px solid;
            backdrop-filter: blur(4px);
        }

        .badge-csrd { border-color: #5CCC6D; color: #5CCC6D; }
        .badge-gri { border-color: #90C335; color: #90C335; }
        .badge-issb { border-color: #A076FF; color: #A076FF; }
        .badge-taxonomy { border-color: #4DACFD; color: #47AAFD; }

        /* Company Information */
        .company-info {
            background: #F5F7FA;
            padding: 2.5rem;
            border-left: 8px solid #D6C4FF;
            margin-bottom: 1.25rem;
        }

        .company-info h2 {
            font-size: 1.5rem;
            font-weight: 700;
            color: #D6C4FF;
            margin-bottom: 1.5rem;
            letter-spacing: -0.6px;
        }

        .info-grid {
            display: grid;
            grid-template-columns: repeat(auto-fit, minmax(200px, 1fr));
            gap: 1.5rem;
        }

        .info-item {
            font-size: 0.875rem;
        }

        .info-label {
            color: #6b7280;
            margin-bottom: 0.25rem;
        }

        .info-value {
            color: #1f2937;
            font-weight: 600;
        }

        /* Executive Summary */
        .executive-summary {
            padding: 2.5rem;
            border-radius: 1.5rem;
            margin: 1rem;
            border: 2px solid #f0fbe7;
        }

        .section-header {
            display: flex;
            align-items: center;
            margin-bottom: 1.5rem;
        }

        .section-icon {
            padding: 0.75rem;
            border-radius: 0.75rem;
            margin-right: 1rem;
            background: #7ed321;
        }

        .section-title {
            font-size: 2rem;
            font-weight: 700;
        }

        .section-subtitle {
            font-weight: 600;
            color: #7ed422;
        }

        .summary-text {
            color: #374151;
            margin-bottom: 2rem;
            line-height: 1.6;
        }

        /* Metrics Grid */
        .metrics-grid {
            display: grid;
            grid-template-columns: repeat(auto-fit, minmax(250px, 1fr));
            gap: 1.5rem;
            margin: 2rem 0;
        }

        .metric-card {
            padding: 2rem;
            border-radius: 1.5rem;
            text-align: center;
            transition: transform 0.2s;
            background: white;
            border: 2px solid;
        }

        .metric-card:hover {
            transform: translateY(-2px);
        }

        .metric-card.green { border-color: #7ed422; }
        .metric-card.orange { border-color: #feae8a; }
        .metric-card.purple { border-color: #ba9eff; }
        .metric-card.blue { border-color: #48aafd; }

        .metric-value {
            font-size: clamp(1.5rem, 4vw, 2rem);
            font-weight: 900;
            margin-bottom: 0.5rem;
        }

        .metric-value.green { color: #5BCC6D; }
        .metric-value.orange { color: #FFA726; }
        .metric-value.purple { color: #D6C4FF; }
        .metric-value.blue { color: #29B6F6; }

        .metric-label {
            font-size: 0.875rem;
            font-weight: 700;
            margin-bottom: 0.75rem;
        }

        .metric-label.green { color: #5BCC6D; }
        .metric-label.orange { color: #FFA726; }
        .metric-label.purple { color: #D6C4FF; }
        .metric-label.blue { color: #29B6F6; }

        .metric-trend {
            font-size: 0.75rem;
            padding: 0.25rem 0.75rem;
            border-radius: 1rem;
            font-weight: 700;
            color: white;
        }

        .trend-green { background: #5BCC6D; }
        .trend-orange { background: #FFA726; }
        .trend-purple { background: #D6C4FF; }
        .trend-blue { background: #29B6F6; }

        /* CSRD Section */
        .csrd-section {
            padding: 2.5rem;
        }

        .csrd-header {
            background: #F5F7FA;
            padding: 2rem;
            border-radius: 1.5rem;
            margin-bottom: 2rem;
            display: flex;
            align-items: center;
        }

        .csrd-number {
            background: #D6C4FF;
            padding: 0.5rem 0.75rem;
            border-radius: 0.75rem;
            font-weight: 900;
            margin-right: 1.5rem;
        }

        .csrd-title {
            font-size: clamp(1.5rem, 5vw, 2rem);
            font-weight: 700;
            color: #000000;
            letter-spacing: -0.6px;
        }

        .csrd-description {
            color: #111827;
            font-weight: 500;
        }

        /* Disclosure Items */
        .disclosure-grid {
            display: grid;
            gap: 1.5rem;
        }

        .disclosure-item {
            border: 1px solid #e5e7eb;
            border-radius: 0.75rem;
            padding: 1.5rem;
            border-left: 4px solid #059669;
        }

        .disclosure-header {
            display: flex;
            justify-content: space-between;
            align-items: flex-start;
            margin-bottom: 1rem;
        }

        .disclosure-code {
            background: #f3f4f6;
            padding: 0.375rem 0.75rem;
            border-radius: 0.375rem;
            font-family: 'Monaco', 'Menlo', monospace;
            font-size: 0.75rem;
            font-weight: 600;
            color: #374151;
            margin-bottom: 0.5rem;
        }

        .disclosure-title {
            font-size: 1.125rem;
            font-weight: 600;
            color: #1f2937;
        }

        .compliance-badge {
            background: rgba(184, 233, 134, 0.2);
            color: #417505;
            padding: 0.25rem 0.75rem;
            border-radius: 1rem;
            font-size: 0.75rem;
            font-weight: 600;
        }

        /* Emissions Grid */
        .emissions-grid {
            display: grid;
            grid-template-columns: repeat(auto-fit, minmax(150px, 1fr));
            gap: 1rem;
            margin-top: 1rem;
        }

        .emission-item {
            text-align: center;
            padding: 1rem;
            background: #f9fafb;
            border-radius: 0.5rem;
        }

        .emission-value {
            font-size: 1.125rem;
            font-weight: 700;
            margin-bottom: 0.25rem;
        }

        .emission-value.scope1 { color: #5BCC6D; }
        .emission-value.scope2 { color: #29B6F6; }
        .emission-value.scope3 { color: #D6C4FF; }

        .emission-label {
            font-size: 0.75rem;
            color: #6b7280;
        }

        /* Data Sources */
        .data-section {
            padding: 2.5rem;
        }

        .verification-box {
            background: #D6C4FF;
            padding: 1.5rem;
            border-radius: 1rem;
            margin-bottom: 2rem;
            text-align: center;
        }

        .verification-title {
            font-size: 1.125rem;
            font-weight: 700;
            color: white;
            margin-bottom: 1rem;
        }

        .verification-stats {
            display: grid;
            grid-template-columns: repeat(auto-fit, minmax(120px, 1fr));
            gap: 1rem;
            color: white;
            font-size: 0.875rem;
        }

        .verification-stat span {
            font-weight: 700;
            display: block;
        }

        .source-list {
            display: grid;
            gap: 1rem;
        }

        .source-item {
            display: flex;
            align-items: center;
            justify-content: space-between;
            padding: 1rem;
            border-radius: 1rem;
            border: 2px solid;
            background: white;
        }

        .source-item.energy { border-color: #fff9c4; }
        .source-item.fuel { border-color: #ffedd6; }
        .source-item.supplier { border-color: #dceaff; }
        .source-item.waste { border-color: #ddfde8; }

        .source-info {
            display: flex;
            align-items: center;
        }

        .source-icon {
            font-size: 1.5rem;
            padding: 0.75rem;
            border-radius: 0.75rem;
            margin-right: 1rem;
        }

        .source-icon.energy { background: #fef3e0; }
        .source-icon.fuel { background: #fff3e0; }
        .source-icon.supplier { background: #e3f2fd; }
        .source-icon.waste { background: #e8f5e8; }

        .source-details h4 {
            font-weight: 700;
            color: #1f2937;
            margin-bottom: 0.25rem;
        }

        .source-meta {
            font-size: 0.75rem;
            color: #6b7280;
        }

        .source-impact {
            font-weight: 700;
            padding: 0.5rem 1rem;
            border-radius: 0.75rem;
        }

        .impact-positive { background: #e8f5e8; color: #5BCC6D; }
        .impact-negative { background: #fff3e0; color: #FFA726; }

        /* Verification Stamp */
        .verification-stamp {
            background: linear-gradient(135deg, #059669 0%, #047857 100%);
            color: white;
            padding: 2rem;
            border-radius: 1rem;
            text-align: center;
            margin: 2rem;
        }

        .stamp-icon {
            font-size: 3rem;
            margin-bottom: 1rem;
        }

        .stamp-title {
            font-size: 1.5rem;
            font-weight: 700;
            margin-bottom: 0.5rem;
        }

        .stamp-subtitle {
            font-size: 0.875rem;
            opacity: 0.9;
            line-height: 1.5;
        }

        /* Footer */
        .footer {
            background: linear-gradient(135deg, #1f2937 0%, #111827 100%);
            color: white;
            padding: 3rem;
            text-align: center;
        }

        .footer-logo {
            font-size: 1.5rem;
            font-weight: 700;
            color: #059669;
            margin-bottom: 1rem;
        }

        .footer-content {
            max-width: 800px;
            margin: 0 auto;
        }

        .footer p {
            margin-bottom: 1rem;
            line-height: 1.6;
        }

        .footer-stats {
            display: grid;
            grid-template-columns: repeat(auto-fit, minmax(200px, 1fr));
            gap: 2rem;
            margin: 2rem 0;
            font-size: 0.875rem;
        }

        .footer-stat h4 {
            color: #10b981;
            font-weight: 700;
            margin-bottom: 0.5rem;
        }

        .footer-stat p {
            color: #9ca3af;
            margin: 0;
        }

        @media print {
            body { background: white; }
            .container { box-shadow: none; }
            .verification-stamp, .footer { page-break-inside: avoid; }
        }
    </style>
</head>
<body>
    <div class="container">
        <!-- Header -->
        <div class="header">
            <div class="logo-section">
                <img src="data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 100 20'%3E%3Ctext x='0' y='15' font-family='Inter' font-weight='800' font-size='16' fill='%23059669'%3EENVOCAP%3C/text%3E%3C/svg%3E" alt="ENVOCAP" class="logo">
            </div>
            <h1 class="main-title">
                Corporate Sustainability<br>
                Reporting Directive
            </h1>
            <div class="subtitle">ESG Disclosure Report 2024 • CSRD Compliant</div>
            <div class="compliance-badges">
                <div class="badge badge-csrd">✓ CSRD COMPLIANT</div>
                <div class="badge badge-gri">✓ GRI STANDARDS</div>
                <div class="badge badge-issb">✓ ISSB ALIGNED</div>
                <div class="badge badge-taxonomy">✓ EU TAXONOMY</div>
            </div>
        </div>

        <!-- Company Information -->
        <div class="company-info">
            <h2>Report Information</h2>
            <div class="info-grid">
                <div class="info-item">
                    <div class="info-label">Company Name</div>
                    <div class="info-value">Green Solutions Ltd</div>
                </div>
                <div class="info-item">
                    <div class="info-label">Industry Sector</div>
                    <div class="info-value">Manufacturing (NACE Code C25)</div>
                </div>
                <div class="info-item">
                    <div class="info-label">Reporting Period</div>
                    <div class="info-value">FY 2024 (January 1 - December 31, 2024)</div>
                </div>
                <div class="info-item">
                    <div class="info-label">Report ID</div>
                    <div class="info-value">${reportId}</div>
                </div>
                <div class="info-item">
                    <div class="info-label">Generated Date</div>
                    <div class="info-value">${currentDate}</div>
                </div>
                <div class="info-item">
                    <div class="info-label">Prepared By</div>
                    <div class="info-value">ENVOCAP Platform</div>
                </div>
            </div>
        </div>

        <!-- Executive Summary -->
        <div class="executive-summary">
            <div class="section-header">
                <div class="section-icon">����</div>
                <div>
                    <h2 class="section-title">Executive Summary</h2>
                    <div class="section-subtitle">Key Performance Highlights</div>
                </div>
            </div>
            <p class="summary-text">
                This Corporate Sustainability Reporting Directive (CSRD) compliant report presents Green Solutions Ltd's
                environmental, social, and governance performance for the 2024 fiscal year. Our comprehensive approach to
                sustainability demonstrates a <strong>12% reduction in carbon emissions</strong> and <strong>94% compliance</strong>
                with CSRD requirements, reflecting our commitment to the European Green Deal objectives.
            </p>

            <div class="metrics-grid">
                <div class="metric-card green">
                    <div class="metric-value green">24.8 tCO₂</div>
                    <div class="metric-label green">Scope 1 & 2 Emissions</div>
                    <div class="metric-trend trend-green">↓ 12% vs. 2023</div>
                </div>
                <div class="metric-card orange">
                    <div class="metric-value orange">156.2 MWh</div>
                    <div class="metric-label orange">Energy Consumption</div>
                    <div class="metric-trend trend-orange">↑ 3% vs. 2023</div>
                </div>
                <div class="metric-card purple">
                    <div class="metric-value purple">€2.1M</div>
                    <div class="metric-label purple">Green Investments</div>
                    <div class="metric-trend trend-purple">↑ 45% vs. 2023</div>
                </div>
                <div class="metric-card blue">
                    <div class="metric-value blue">94%</div>
                    <div class="metric-label blue">CSRD Compliance Score</div>
                    <div class="metric-trend trend-blue">Target: 90%</div>
                </div>
            </div>
        </div>

        <!-- CSRD Environmental Disclosures -->
        <div class="csrd-section">
            <div class="csrd-header">
                <div class="csrd-number">E1</div>
                <div>
                    <h2 class="csrd-title">Climate Change</h2>
                    <p class="csrd-description">Environmental disclosure requirements under CSRD</p>
                </div>
            </div>

            <div class="disclosure-grid">
                <div class="disclosure-item">
                    <div class="disclosure-header">
                        <div>
                            <div class="disclosure-code">CSRD E1-1</div>
                            <h4 class="disclosure-title">Transition Plan for Climate Change Mitigation</h4>
                        </div>
                        <div class="compliance-badge">✓ COMPLIANT</div>
                    </div>
                    <p>Comprehensive climate transition plan targeting net-zero emissions by 2050, with interim targets of 50% reduction by 2030.</p>
                </div>

                <div class="disclosure-item">
                    <div class="disclosure-header">
                        <div>
                            <div class="disclosure-code">CSRD E1-6</div>
                            <h4 class="disclosure-title">Gross Scopes 1, 2, 3 GHG Emissions</h4>
                        </div>
                        <div class="compliance-badge">✓ COMPLIANT</div>
                    </div>
                    <div class="emissions-grid">
                        <div class="emission-item">
                            <div class="emission-value scope1">8.2 tCO₂</div>
                            <div class="emission-label">Scope 1 (Direct)</div>
                        </div>
                        <div class="emission-item">
                            <div class="emission-value scope2">16.6 tCO₂</div>
                            <div class="emission-label">Scope 2 (Indirect)</div>
                        </div>
                        <div class="emission-item">
                            <div class="emission-value scope3">12.4 tCO₂</div>
                            <div class="emission-label">Scope 3 (Value Chain)</div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <!-- Data Sources -->
        <div class="data-section">
            <div class="section-header">
                <div class="section-icon" style="background: #8042ff;">📋</div>
                <div>
                    <h3 class="section-title">Data Sources & Audit Trail</h3>
                    <div class="csrd-description">Complete traceability and verification</div>
                </div>
            </div>

            <div class="verification-box">
                <div class="verification-title">🛡️ Verification Summary</div>
                <div class="verification-stats">
                    <div class="verification-stat">
                        <span>127</span>
                        Documents Processed
                    </div>
                    <div class="verification-stat">
                        <span>100%</span>
                        Verification Rate
                    </div>
                    <div class="verification-stat">
                        <span>37.2</span>
                        Total tCO₂ Tracked
                    </div>
                    <div class="verification-stat">
                        <span>94%</span>
                        Data Quality Score
                    </div>
                </div>
            </div>

            <div class="source-list">
                <div class="source-item energy">
                    <div class="source-info">
                        <div class="source-icon energy">⚡</div>
                        <div class="source-details">
                            <h4>November Energy Bill - Green Energy Solutions Ltd</h4>
                            <div class="source-meta">PDF • 2.4MB • OCR: 98.7% • Renewable certificate verified</div>
                        </div>
                    </div>
                    <div class="source-impact impact-negative">+2.1 tCO₂</div>
                </div>

                <div class="source-item fuel">
                    <div class="source-info">
                        <div class="source-icon fuel">⛽</div>
                        <div class="source-details">
                            <h4>Fleet Fuel Receipts - Q4 2024</h4>
                            <div class="source-meta">CSV • 156 transactions • GPS verified • Vehicle cross-ref</div>
                        </div>
                    </div>
                    <div class="source-impact impact-negative">+1.8 tCO₂</div>
                </div>

                <div class="source-item supplier">
                    <div class="source-info">
                        <div class="source-icon supplier">🤝</div>
                        <div class="source-details">
                            <h4>Supplier Sustainability Data - 23 partners</h4>
                            <div class="source-meta">XLSX • 89% response • ISO 14001 verified</div>
                        </div>
                    </div>
                    <div class="source-impact impact-negative">+0.9 tCO₂</div>
                </div>

                <div class="source-item waste">
                    <div class="source-info">
                        <div class="source-icon waste">📱</div>
                        <div class="source-details">
                            <h4>Camera Scan - Office Waste Report</h4>
                            <div class="source-meta">JPG (OCR) • AI: 96.4% accuracy • 85% recycling rate</div>
                        </div>
                    </div>
                    <div class="source-impact impact-positive">-0.3 tCO₂</div>
                </div>
            </div>
        </div>

        <!-- Verification Stamp -->
        <div class="verification-stamp">
            <div class="stamp-icon">🛡️</div>
            <div class="stamp-title">AUDIT-READY REPORT</div>
            <div class="stamp-subtitle">
                ✓ Generated and verified by ENVOCAP AI Platform<br>
                ✓ Compliant with CSRD, GRI, and ISSB standards<br>
                ✓ Report ID: ${reportId}
            </div>
        </div>

        <!-- Footer -->
        <div class="footer">
            <div class="footer-content">
                <div class="footer-logo">🌿 ENVOCAP</div>
                <p><strong>This is a sample report demonstrating ENVOCAP's capabilities.</strong></p>
                <p>For full functionality, regulatory updates, and continuous compliance monitoring, upgrade to ENVOCAP Pro.</p>

                <div class="footer-stats">
                    <div class="footer-stat">
                        <h4>🌍 Global Compliance</h4>
                        <p>CSRD, GRI, ISSB, TCFD, SASB</p>
                    </div>
                    <div class="footer-stat">
                        <h4>🤖 AI-Powered</h4>
                        <p>OCR, NLP, Data Verification</p>
                    </div>
                    <div class="footer-stat">
                        <h4>🔒 Enterprise Security</h4>
                        <p>SOC2, GDPR, ISO 27001</p>
                    </div>
                </div>

                <p>© 2024 ENVOCAP Platform. All rights reserved. | envocap.com | contact@envocap.com</p>
                <p style="font-size: 0.75rem; margin-top: 1rem; color: #9ca3af;">
                    Generated in compliance with Commission Delegated Regulation (EU) 2023/2772 - CSRD
                </p>
            </div>
        </div>
    </div>
</body>
</html>
  `;
};

// Enhanced download function with both PDF and HTML options
export const downloadStyledReport = () => {
  // Offer HTML version with full styling
  const htmlContent = generateStyledHTMLReport();
  const blob = new Blob([htmlContent], { type: 'text/html' });
  const url = URL.createObjectURL(blob);

  const link = document.createElement('a');
  link.href = url;
  link.download = 'ENVOCAP_Styled_ESG_Report_2024.html';
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);

  URL.revokeObjectURL(url);

  // Show user instruction for printing to PDF
  setTimeout(() => {
    alert('HTML report downloaded! To get a PDF with full styling:\n\n1. Open the downloaded HTML file in your browser\n2. Press Ctrl+P (or Cmd+P on Mac)\n3. Select "Save as PDF" as destination\n4. Choose "More settings" and enable "Background graphics"\n5. Click "Save"\n\nThis will preserve all the colors, gradients, and styling!');
  }, 500);
};

// Generate HTML report as fallback
export const generateHTMLReport = generateStyledHTMLReport;
